@startuml
'https://plantuml.com/sequence-diagram

autonumber

AuthResponseDTO -> JWTTokenService: Authentication Request
JWTTokenService --> AuthResponseDTO: Authentication Response

AuthResponseDTO -> JWTTokenService: Another authentication Request
JWTTokenService <-- AuthResponseDTO: another authentication Response
@enduml